export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTICLES_REQUEST'
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS'
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTICLES_FAILURE'

export const FETCH_ARTICLE_BY_SLUG_REQUEST = 'FETCH_ARTICLE_BY_SLUG_REQUEST'
export const FETCH_ARTICLE_BY_SLUG_SUCCESS = 'FETCH_ARTICLE_BY_SLUG_SUCCESS'
export const FETCH_ARTICLE_BY_SLUG_FAILURE = 'FETCH_ARTICLE_BY_SLUG_FAILURE'

export const POST_CREATE_NEW_ACCOUNT_REQUEST = 'POST_CREATE_NEW_ACCOUNT_REQUEST'
export const POST_NEW_ACCOUNT_SUCCESS = 'POST_NEW_ACCOUNT_SUCCESS'
export const POST_NEW_ACCOUNT_FAILURE = 'POST_NEW_ACCOUNT_FAILURE'
export const POST_NEW_ACCOUNT_SERVER_FAIL = 'POST_NEW_ACCOUNT_SERVER_FAIL'

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST'
export const POST_LOGIN_SUCCES = 'POST_LOGIN_SUCCES'
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE'
export const POST_LOGIN_SERVER_FAIL = 'POST_LOGIN_SERVER_FAIL'

export const LOGOUT = 'LOGOUT'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'