export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTICLES_REQUEST'
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTICLES_SUCCESS'
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTICLES_FAILURE'

export const FETCH_ARTICLE_BY_SLUG_REQUEST = 'FETCH_ARTICLE_BY_SLUG_REQUEST'
export const FETCH_ARTICLE_BY_SLUG_SUCCESS = 'FETCH_ARTICLE_BY_SLUG_SUCCESS'
export const FETCH_ARTICLE_BY_SLUG_FAILURE = 'FETCH_ARTICLE_BY_SLUG_FAILURE'